[package]
name = "rns-proxy"
description = "SOCKS5 proxy client & server over Reticulum Network Stack"
version = "0.1.0"
license = "MIT"
edition = "2021"

[[bin]]
name = "rns-proxy"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.53", features = ["full"] }
fast-socks5 = "1.0"
hex = "0.4"
udp-stream = "0.0.12"

rns-net =  { git = "https://github.com/lelloman/rns-rs.git" , branch = "dev"}
rns-core = { git = "https://github.com/lelloman/rns-rs.git" , branch = "dev"}
rns-crypto = { git = "https://github.com/lelloman/rns-rs.git" , branch = "dev"}
prse = "1.2.1"
